version: '3.7'

services:
  domoticz:
    image: linuxserver/domoticz
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - domoticz_config:/config
    deploy:
      constraints: 
        - node.labels.domoticz.domoticz-data == true

volumes:
  domoticz_config:
